[package]
name = "resvg"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "An SVG rendering library."
keywords = ["svg", "render", "raster"]
exclude = ["tests"]
workspace = "../.."

[[bin]]
name = "resvg"
required-features = ["svgz", "text", "system-fonts", "memmap-fonts"]

[dependencies]
gif = { workspace = true, optional = true }
image-webp = { workspace = true, optional = true }
log = { workspace = true }
pico-args = { workspace = true, features = ["eq-separator"] }
rgb = { workspace = true }
svgtypes = { workspace = true }
tiny-skia = { workspace = true }
usvg = { workspace = true }
zune-jpeg = { workspace = true, optional = true }

[dev-dependencies]
once_cell = { workspace = true }
png = { workspace = true }

[features]
default = ["svgz", "text", "system-fonts", "memmap-fonts", "raster-images"]
# Enables SVGZ decoding
svgz = ["usvg/svgz"]
# Enables SVG Text support.
# Adds around 400KiB to your binary.
text = ["usvg/text"]
# Enables system fonts loading (only for `text`).
system-fonts = ["usvg/system-fonts"]
# Enables font files memmaping for faster loading (only for `text`).
memmap-fonts = ["usvg/memmap-fonts"]
# Enables decoding and rendering of raster images.
# When disabled, `image` elements with SVG data will still be rendered.
# Adds around 200KiB to your binary.
raster-images = ["gif", "image-webp", "dep:zune-jpeg"]
