[workspace]
members = [
    "crates/c-api",
    "crates/resvg",
    "crates/usvg",
    "crates/usvg/codegen",
    #"tools/explorer-thumbnailer",
]
default-members = ["crates/resvg"]
resolver = "2"

[workspace.package]
version = "0.47.0"
license = "Apache-2.0 OR MIT"
rust-version = "1.89.0"
edition = "2024"
repository = "https://github.com/linebender/resvg"

[workspace.dependencies]
# In-repo dependencies
usvg = { path = "./crates/usvg", version = "0.47.0", default-features = false }
resvg = { path = "./crates/resvg", default-features = false }
resvg-capi = { path = "./crates/c-api", default-features = false }

# Misc / General

log = "0.4"
once_cell = "1.21"

# Tiny Skia
tiny-skia = "0.12.0"
tiny-skia-path = "0.12.0"

# resvg-associated crates
pico-args = "0.5"
strict-num = "0.2.0"
svgtypes = "0.16.1"
xmlwriter = "0.1"

# parser
data-url = "0.3" # for href parsing
flate2 = { version = "1.1", default-features = false } # SVGZ decoding
imagesize = "0.15.0" # raster images size detection
kurbo = "0.13.0" # Bezier curves utils
roxmltree = "0.21.1"
simplecss = "0.2"
siphasher = "1.0" # perfect hash implementation

# text
fontdb = { version = "0.24", default-features = false }
harfrust = "0.12.0"
skrifa = { version = "0.44", default-features = false }
unicode-bidi = "0.3"
unicode-script = "0.5"
unicode-vo = "0.1"

# Images
gif = "0.14.1" 
image-webp = "0.2.4"
rgb = "0.8"
zune-jpeg = "0.5.9"
png = "0.18.0"
base64 = "0.23" # for embedded images

[profile.production]
inherits = "release"
opt-level = 3
debug = false
lto = true
codegen-units = 1
strip = true
incremental = false
