[package]
name = "usvg"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "An SVG simplification library."
keywords = ["svg"]
categories = ["multimedia::images"]
documentation = "https://docs.rs/usvg/"
readme = "README.md"
exclude = ["tests"]
workspace = "../.."

[[bin]]
name = "usvg"
required-features = ["svgz", "text", "system-fonts", "memmap-fonts", "writer"]

[dependencies]
base64 = { workspace = true, optional = true } # for embedded images
log = { workspace = true }
pico-args = { workspace = true, features = ["eq-separator"] }
strict-num = { workspace = true }
svgtypes = { workspace = true }
tiny-skia-path = { workspace = true }
xmlwriter = { workspace = true, optional = true }

# parser
data-url = { workspace = true } # for href parsing
flate2 = { workspace = true, default-features = false, features = ["rust_backend"], optional = true } # SVGZ decoding
imagesize = { workspace = true } # raster images size detection
kurbo = { workspace = true } # Bezier curves utils
roxmltree = { workspace = true }
simplecss = { workspace = true }
siphasher = { workspace = true } # perfect hash implementation

# text
fontdb = { workspace = true, default-features = false, optional = true }
harfrust = { workspace = true, optional = true }
skrifa = { workspace = true, optional = true, default-features = false, features = ["std"] }
unicode-bidi = { workspace = true, optional = true }
unicode-script = { workspace = true, optional = true }
unicode-vo = { workspace = true, optional = true }

[dev-dependencies]
once_cell = { workspace = true }

[features]
default = ["svgz", "text", "system-fonts", "memmap-fonts", "writer"]
# Enables SVGZ decoding
svgz = ["flate2"]
# Enables text-to-path conversion support.
# Adds around 400KiB to your binary.
text = ["fontdb", "harfrust", "skrifa", "unicode-bidi", "unicode-script", "unicode-vo", "writer"]
# Enables system fonts loading.
system-fonts = ["fontdb/fs", "fontdb/fontconfig"]
# Enables font files memmaping for faster loading.
memmap-fonts = ["fontdb/memmap"]
# Enables converting trees back to SVG.
writer = ["xmlwriter", "base64"]
