[package]
name = "resvg-capi"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
keywords = ["svg", "render", "raster", "c-api"]
workspace = "../.."

[lib]
name = "resvg"
path = "lib.rs"
crate-type = ["cdylib", "staticlib"]

[dependencies]
log = { workspace = true }
resvg = { workspace = true, default-features = false }

[features]
default = ["svgz", "text", "system-fonts", "memmap-fonts", "raster-images"]
# Enables SVGZ decoding
svgz = ["resvg/svgz"]
# enables SVG Text support
# adds around 500KiB to your binary
text = ["resvg/text"]
# enables system fonts loading (only for `text`)
system-fonts = ["resvg/system-fonts"]
# enables font files memmaping for faster loading (only for `text`)
memmap-fonts = ["resvg/memmap-fonts"]
raster-images = ["resvg/raster-images"]
capi = []

[package.metadata.capi.header]
generation = false

[package.metadata.capi.install.include]
asset = [{ from="resvg.h" }]
